name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./front
    steps:
      - uses: actions/checkout@v2
      - name: Run install
        run: yarn
      - name: Run tests
        run: npm run test:unit
